version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      SCRAPER_MYSQL_DSN: ${SCRAPER_MYSQL_DSN}
      MYSQL_DSN: ${MYSQL_DSN}
      SERVER_ADDRESS: ${SERVER_ADDRESS}

  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '3333:3306'
    volumes:
      - 'mysql_gophersignal:/var/lib/mysql'

volumes:
  mysql_gophersignal:
    driver: local
