version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    networks:
      - app-network

  backend:
    image: kjzehnder3/gophersignal:backend-latest
    ports:
      - 8080:8080
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - MYSQL_DSN
      - SERVER_ADDRESS

  mysql:
    image: mysql:latest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - mysql_gophersignal:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

networks:
  app-network:
    driver: bridge

volumes:
  mysql_gophersignal:
    driver: local
