services:
  frontend:
    image: kjzehnder3/gophersignal-frontend:latest
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env
    restart: unless-stopped

  backend:
    image: kjzehnder3/gophersignal-backend:latest
    ports:
      - 8080:8080
    networks:
      - app-network
    env_file:
      - .env
    restart: unless-stopped

  hackernews_scraper:
    image: kjzehnder3/gophersignal-hackernews_scraper:latest
    networks:
      - app-network
    env_file:
      - .env
    restart: unless-stopped

  rss:
    image: kjzehnder3/gophersignal-rss:latest
    ports:
      - 9090:9090
    networks:
      - app-network
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/production.conf:/etc/nginx/nginx.conf
      - ./frontend/out:/usr/share/nginx/html
    depends_on:
      - backend
      - rss
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  ollama:
    driver: local
