version: '3.8'

services:
  app:
    build: ./backend
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/var/www/gophersignal.com/html
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3333:3306"  
    volumes:
      - mysql_gophersignal:/var/lib/mysql

volumes:
  mysql_gophersignal:
    driver: local
