services:
  frontend:
    image: kjzehnder3/gophersignal-frontend:latest
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: kjzehnder3/gophersignal-backend:latest
    ports:
      - 8080:8080
    networks:
      - app-network
    env_file:
      - .env
<<<<<<< HEAD
    depends_on:
      mysql:
        condition: service_healthy
=======
    restart: always
>>>>>>> origin/staging

  hackernews_scraper:
    image: kjzehnder3/gophersignal-hackernews_scraper:latest
    networks:
      - app-network
    env_file:
      - .env

<<<<<<< HEAD
  mysql:
    image: mysql:latest
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - mysql_gophersignal:/var/lib/mysql
    networks:
      - app-network
    env_file:
      - .env

=======
>>>>>>> origin/staging
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/production.conf:/etc/nginx/nginx.conf
      - ./frontend/out:/usr/share/nginx/html
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

