version: '3.8'

services:
  app:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3333:3306"
    volumes:
      - mysql_gophersignal:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/gophersignal.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/gophersignal.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/ssl/options-ssl-nginx.conf:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/ssl/ssl-dhparams.pem:ro

volumes:
  mysql_gophersignal:
    driver: local
