# Use the official Go image as the base image
FROM golang:latest

# Set the working directory for your application
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Install netcat
RUN apt-get update && apt-get install -y netcat-traditional

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Copy the entrypoint script
COPY bin/entrypoint.sh /entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x /entrypoint.sh

# Set the entrypoint to the script
ENTRYPOINT ["/entrypoint.sh"]
