version: '3.8'

services:
  app:
    build: .
    ports:
      - "8333:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      DB_NAME: ${DB_NAME}

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3333:3306"
    volumes:
      - mysql_gophersignal:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql_gophersignal:
    driver: local
