version: '3.8'

services:
  app:
    build: .
    ports:
      - "8333:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3333:3306"
    volumes:
      - mysql_gophersignal_latest:/var/lib/mysql

volumes:
  mysql_gophersignal_latest:
    driver: local
