# Use the official Golang image as the base image
FROM golang:latest

# Install necessary packages
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    wget

# Install swag CLI for generating Swagger docs
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Set the working directory for your application
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Generate Swagger docs
RUN swag init

# Verify Swagger docs generation
RUN test -f docs/swagger.json && test -f docs/swagger.yaml

# Ensure init-db.sh is executable
RUN chmod +x /app/bin/init-db.sh

# Expose port 8080
EXPOSE 8080

# Run the initialization script and start the Go application
CMD ["/app/bin/init-db.sh"]
