# Use the official Debian-based Go image
FROM golang:1.20

# Set the working directory for the application
WORKDIR /app

# Install MySQL client using apt-get
RUN apt-get update && apt-get install -y default-mysql-client

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Generate Swagger docs
RUN swag init

# Verify Swagger docs generation
RUN test -f docs/swagger.json && test -f docs/swagger.yaml

# Ensure init-db.sh is executable
RUN chmod +x /app/init-db.sh

# Run the initialization script and start the Go application
CMD ["/app/init-db.sh"]
