basePath: /api/v1
definitions:
  models.ArticleResponse:
    properties:
      content:
        description: 'Full content of the article (default: "")'
        type: string
      created_at:
        description: 'Timestamp of when the article was created (default: current
          time)'
        type: string
      id:
        description: 'Unique identifier of the article (default: 0)'
        type: integer
      is_on_homepage:
        description: 'Flag indicating if the article is displayed on the homepage
          (default: false)'
        type: boolean
      link:
        description: 'External link to the article (default: "")'
        type: string
      source:
        description: 'Source from where the article was obtained (default: "")'
        type: string
      summary:
        description: 'Brief summary of the article (default: "")'
        type: string
      title:
        description: 'Title of the article (default: "")'
        type: string
      updated_at:
        description: 'Timestamp of the last update to the article (default: current
          time)'
        type: string
    type: object
  models.Response:
    properties:
      code:
        description: 'The HTTP status code of the response (default: 200)'
        type: integer
      data:
        description: The data payload of the response
      status:
        description: 'The status message accompanying the code (default: "success")'
        type: string
    type: object
host: gophersignal.com
info:
  contact: {}
  description: This is the GopherSignal API server.
  title: GopherSignal API
  version: "1"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Retrieve a list of articles from the database.
      parameters:
      - default: true
        description: Filter by is_on_homepage
        in: query
        name: is_on_homepage
        type: boolean
      - default: 100
        description: Maximum number of articles to return
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ArticleResponse'
            type: array
        "400":
          description: Invalid Query Parameter
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Get articles
      tags:
      - Articles
swagger: "2.0"
