basePath: /api/v1
definitions:
  models.ArticleResponse:
    properties:
      content:
        type: string
      id:
        type: integer
      link:
        type: string
      source:
        type: string
      summary:
        type: string
      title:
        type: string
    type: object
  models.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: gophersignal.com
info:
  contact: {}
  description: This is the GopherSignal API server.
  title: GopherSignal API
  version: "1"
  x-logo:
    altText: GopherSignal Logo
    url: https://sdtimes.com/wp-content/uploads/2021/03/Go-gopher.jpg
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Retrieve a list of articles from the database.
      parameters:
      - default: true
        description: Filter by is_on_homepage
        in: query
        name: is_on_homepage
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ArticleResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Get articles
      tags:
      - Articles
swagger: "2.0"
