basePath: /api/v1
definitions:
  models.ArticleResponse:
    properties:
      content:
        description: 'Full content of the article (default: ""), example: "Sample
          content..."'
        type: string
      created_at:
        description: 'Timestamp of when the article was created (default: current
          time), example: "2022-01-01T12:00:00Z"'
        type: string
      id:
        description: 'Unique identifier of the article (default: 0), example: 1'
        type: integer
      link:
        description: 'External link to the article (default: ""), example: "https://example.com"'
        type: string
      source:
        description: 'Source from where the article was obtained (default: ""), example:
          "Sample Source"'
        type: string
      summary:
        description: 'Brief summary of the article (default: ""), example: "This is
          a sample summary."'
        type: string
      title:
        description: 'Title of the article (default: ""), example: "Sample Title"'
        type: string
      updated_at:
        description: 'Timestamp of the last update to the article (default: current
          time), example: "2022-01-01T12:30:00Z"'
        type: string
    type: object
  models.Response:
    properties:
      code:
        description: 'The HTTP status code of the response (default: 200)'
        type: integer
      data:
        description: The data payload of the response
      status:
        description: 'The status message accompanying the code (default: "success")'
        type: string
    type: object
host: gophersignal.com
info:
  contact: {}
  description: API server for the GopherSignal application.
  title: GopherSignal API
  version: "1"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Retrieve a list of articles from the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ArticleResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get articles
      tags:
      - Articles
swagger: "2.0"
