basePath: /api/v1
definitions:
  models.Article:
    properties:
      content:
        description: Full content of the article.
        type: string
      created_at:
        description: Timestamp when the article was created.
        type: string
      id:
        description: Unique identifier for the article.
        type: integer
      link:
        description: URL link to the article.
        type: string
      source:
        description: Source from where the article was fetched.
        type: string
      summary:
        description: Summary of the article, nullable.
        type: string
      title:
        description: Title of the article.
        type: string
      updated_at:
        description: Timestamp when the article was last updated.
        type: string
    type: object
  models.ArticlesResponse:
    properties:
      articles:
        description: List of articles.
        items:
          $ref: '#/definitions/models.Article'
        type: array
      code:
        description: HTTP status code.
        type: integer
      status:
        description: Status message.
        type: string
      total_count:
        description: Total count of articles.
        type: integer
    type: object
  models.ErrorResponse:
    properties:
      code:
        description: HTTP status code.
        type: integer
      message:
        description: Detailed error message.
        type: string
      status:
        description: Error status message.
        type: string
    type: object
info:
  contact: {}
  description: API server for the GopherSignal application.
  title: GopherSignal API
  version: "1"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Retrieve a list of articles from the database.
      produces:
      - application/json
      responses:
        "200":
          description: Articles data
          schema:
            $ref: '#/definitions/models.ArticlesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get articles
      tags:
      - Articles
swagger: "2.0"
