basePath: /api/v1
definitions:
  models.Article:
    properties:
      article_rank:
        description: Article rank extracted from the source.
        type: integer
      comment_count:
        description: Number of comments.
        type: integer
      comment_link:
        description: Link to the comment thread (if any).
        type: string
      content:
        description: Full content of the article.
        type: string
      created_at:
        description: Timestamp when the article was created.
        type: string
      dead:
        description: Whether the article is dead.
        type: boolean
      dupe:
        description: Whether the article is marked as duplicate.
        type: boolean
      flagged:
        description: Whether the article is flagged.
        type: boolean
      id:
        description: Unique identifier for the article.
        type: integer
      link:
        description: URL link to the article.
        type: string
      source:
        description: Source from where the article was fetched.
        type: string
      summary:
        description: Summary of the article, nullable.
        type: string
      title:
        description: Title of the article.
        type: string
      updated_at:
        description: Timestamp when the article was last updated.
        type: string
      upvotes:
        description: Upvote count.
        type: integer
    type: object
  models.ArticlesResponse:
    properties:
      articles:
        description: List of articles.
        items:
          $ref: '#/definitions/models.Article'
        type: array
      code:
        description: HTTP status code.
        type: integer
      status:
        description: Status message.
        type: string
      total_count:
        description: Total count of articles.
        type: integer
    type: object
  models.ErrorResponse:
    properties:
      code:
        description: HTTP status code.
        type: integer
      message:
        description: Detailed error message.
        type: string
      status:
        description: Error status message.
        type: string
    type: object
info:
  contact: {}
  description: API server for the GopherSignal application.
  title: GopherSignal API
  version: "1"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Retrieve a list of articles from the database. Optional query parameters
      parameters:
      - description: Filter by flagged status
        in: query
        name: flagged
        type: boolean
      - description: Filter by dead status
        in: query
        name: dead
        type: boolean
      - description: Filter by duplicate status
        in: query
        name: dupe
        type: boolean
      - default: 30
        description: Limit the number of articles returned (default is 30)
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination (default is 0)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Articles data
          schema:
            $ref: '#/definitions/models.ArticlesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get articles
      tags:
      - Articles
swagger: "2.0"
