basePath: /api/v1
definitions:
  models.ArticleResponse:
    properties:
      content:
        type: string
      id:
        type: integer
      link:
        type: string
      source:
        type: string
      summary:
        type: string
      title:
        type: string
    type: object
  models.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: https://gophersignal.com
info:
  contact: {}
  description: This is the GopherSignal API server.
  title: GopherSignal API
  version: "1"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Retrieve a list of articles from the store
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              allOf:
              - $ref: '#/definitions/models.Response'
              - properties:
                  data:
                    items:
                      $ref: '#/definitions/models.ArticleResponse'
                    type: array
                type: object
            type: array
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Get articles
      tags:
      - articles
swagger: "2.0"
