name: Go

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: cd backend && go get -v -t -d ./...

    - name: Build
      run: cd backend && go build -v ./...

    - name: Run tests
      run: cd backend && go test -v -cover ./...
