name: workflow

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Get dependencies
        run: |
          cd backend
          go get -v -t -d ./...

      - name: Build
        run: |
          cd backend
          go build -v ./...

      - name: Run tests with coverage
        run: |
          cd backend
          go test -v -coverprofile=coverage.out ./...

      - name: Generate coverage HTML report
        run: |
          cd backend
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: backend/coverage.html

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies (Node.js)
        run: |
          cd frontend
          npm install

      - name: Run Cypress tests and capture output
        run: |
          cd frontend
          npx cypress run > cypress-output.txt 2>&1

      - name: Upload Cypress test output
        uses: actions/upload-artifact@v2
        with:
          name: cypress-output
          path: frontend/cypress-output.txt
