name: Workflow (CI)

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set environment variables from GitHub Secrets
      - name: Set Environment Variables (CI)
        run: |
          echo "MYSQL_DSN=${{ secrets.MYSQL_DSN }}" >> $GITHUB_ENV
          echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> $GITHUB_ENV

      # Setup Docker and Docker Compose
      - name: Set up Docker (CI)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Build and start services using Docker Compose (CI)
      - name: Build and Start Services (CI)
        run: |
          docker-compose -f docker-compose.ci.yml up --build -d

      # Run Cypress tests against services in Docker (CI)
      - name: Run Cypress tests (CI)
        run: |
          cd frontend
          npx cypress run | sed 's/\x1b\[[0-9;]*m//g' | tee cypress-output.txt
          if grep -q "All specs passed!" cypress-output.txt; then
            echo "Cypress tests passed"
          else
            echo "Cypress tests failed"
            exit 1
          fi

      # Cleanup Docker Compose services (CI)
      - name: Cleanup Docker Services (CI)
        if: always()
        run: |
          docker-compose -f docker-compose.ci.yml down
