name: workflow

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set environment variables from GitHub Secrets
      - name: Set Environment Variables
        run: |
          echo "MYSQL_DSN=${{ secrets.MYSQL_DSN }}" >> $GITHUB_ENV
          echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> $GITHUB_ENV

      # Setup Docker and Docker Compose
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

      # Build and start services using Docker Compose
      - name: Build and Start Services
        run: |
          docker-compose -f docker-compose.yml up --build -d

      # Setup and test Go backend
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Get Go dependencies
        run: |
          cd backend
          go get -v -t -d ./...

      - name: Build Go application
        run: |
          cd backend
          go build -v ./...

      - name: Run Go tests with coverage
        run: |
          cd backend
          go test -v -coverprofile=coverage.out ./...

      - name: Generate coverage HTML report
        run: |
          cd backend
          go tool cover -html=coverage.out -o coverage.html

      # Upload Go coverage report
      - name: Upload Go coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: backend/coverage.html

      # Setup Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (Node.js)
        run: |
          cd frontend
          npm install

      # Run Cypress tests against services in Docker
      - name: Run Cypress tests
        run: |
          cd frontend
          npx cypress run | sed 's/\x1b\[[0-9;]*m//g' | tee cypress-output.txt
          if grep -q "All specs passed!" cypress-output.txt; then
            echo "Cypress tests passed"
          else
            echo "Cypress tests failed"
            exit 1
          fi

      # Upload Cypress test output
      - name: Upload Cypress test output
        uses: actions/upload-artifact@v3
        with:
          name: cypress-output
          path: frontend/cypress-output.txt

      # Cleanup Docker Compose services
      - name: Cleanup Docker Services
        if: always()
        run: |
          docker-compose -f docker-compose.yml down
