name: workflow

on:
  push:
    branches: [staging]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "MYSQL_DSN=${{ secrets.MYSQL_DSN }}" >> $GITHUB_ENV
          echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> $GITHUB_ENV

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and Start Services
        run: |
          docker-compose -f docker-compose.ci.yml up --build -d

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Get Go dependencies
        run: |
          cd backend
          go get -v -t -d ./...

      - name: Build Go application
        run: |
          cd backend
          go build -v ./...

      - name: Run Go tests with coverage
        run: |
          cd backend
          go test -v -coverprofile=coverage.out ./...

      - name: Generate coverage HTML report
        run: |
          cd backend
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload Go coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: backend/coverage.html

      - name: Wait for Frontend Server
        run: |
          echo "Waiting for the frontend server to be up on http://localhost:3000"
          for i in {1..30}; do
            if curl --head --silent --fail http://localhost:3000; then
              echo "Frontend server is up and running"
              break
            fi
            echo "Waiting for frontend server..."
            sleep 5
          done

      - name: Install Playwright
        run: |
          cd frontend
          npx playwright install
          npx playwright install-deps
          npm install @playwright/test   

      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test

      - name: Upload Playwright test report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-report
          path: frontend/playwright-report

      - name: Cleanup Docker Services
        if: always()
        run: |
          docker-compose -f docker-compose.ci.yml down
